name: Bug Report
description: Something isn't working as expected
labels: [ "Status: Todo", "Type: Bug" ]
assignees: [ "alinco8" ]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
        Please include as much detail as possible so the issue can be reproduced and diagnosed.

  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-flight checklist
      description: Please confirm the following before submitting.
      options:
        - label: I have searched the existing issues to make sure this is not a duplicate.
          required: true
        - label: I confirmed this is not already fixed in the latest version.
          required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual behavior
      description: What actually happened?
      placeholder: I observed...
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: Provide step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Go to...
        2. Click on...
        3. ...
    validations:
      required: true

  - type: input
    id: minecraft_version
    attributes:
      label: Minecraft version
      description: The Minecraft version you are using.
      placeholder: 1.21.1
    validations:
      required: true

  - type: input
    id: mod_version
    attributes:
      label: Mod version
      description: The version of this mod you are using.
      placeholder: 1.2.3
    validations:
      required: true

  - type: input
    id: loader_info
    attributes:
      label: Mod loader and it's version
      description: The mod loader you are using (e.g., NeoForge, Forge, Fabric) and its version.
      placeholder: e.g. NeoForge 21.1.x / Forge 47.3.x / Fabric Loader 0.16.x
    validations:
      required: true

  - type: dropdown
    id: repro_without_other_mods
    attributes:
      label: Reproducible with no other mods?
      description: Did you test whether this happens with only this mod installed?
      options:
        - "Yes"
        - "No (only happens with other mods)"
        - "Not tested"
    validations:
      required: true

  - type: textarea
    id: other_mods
    attributes:
      label: Other mods
      description: List other mods that might be relevant (or write "None/Unknown").
      placeholder: Xaero's Minimap v21.6.0, Xaero's World Map v1.9.6, ...
      render: text
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs (optional)
      description: Paste relevant logs (e.g. latest.log) here, or upload them to mclo.gs and paste the link.
      placeholder: Paste logs here or paste an mclo.gs link...
      render: shell

  - type: textarea
    id: additional_information (optional)
    attributes:
      label: Additional information
      description: Provide any other context or references (links, screenshots, related mods, etc.).
      placeholder: Additional details...
