name: Bug Report
description: Something isn't working as expected
labels: [ "Status: Todo", "Type: Bug" ]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
        Please include as much detail as possible so the issue can be reproduced and diagnosed.

  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-flight checklist
      description: Please confirm the following before submitting.
      options:
        - label: I have searched the existing issues to make sure this is not a duplicate.
          required: true
        - label: I confirmed this is not already fixed in the latest version.
          required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual behavior
      description: What actually happened?
      placeholder: I observed...
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: Provide step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Go to...
        2. Click on...
        3. ...
    validations:
      required: true

  - type: input
    id: minecraft_version
    attributes:
      label: Minecraft version
      description: The Minecraft version you are using.
      placeholder: 1.21.1
    validations:
      required: true

  - type: input
    id: mod_version
    attributes:
      label: Mod version
      description: The version of this mod you are using.
      placeholder: 1.2.3
    validations:
      required: true

  - type: dropdown
    id: loader
    attributes:
      label: Mod loader
      description: Select the mod loader you are using.
      options:
        - NeoForge
        - Forge
        - Fabric
        - Quilt
        - Other
    validations:
      required: true

  - type: input
    id: loader_version
    attributes:
      label: Mod loader version
      description: The version of the mod loader you are using.
      placeholder: e.g. NeoForge 21.1.x / Forge 47.3.x / Fabric Loader 0.16.x
    validations:
      required: true

  - type: dropdown
    id: repro_without_other_mods
    attributes:
      label: Reproducible with no other mods?
      description: Did you test whether this happens with only this mod installed?
      options:
        - Yes
        - No (only happens with other mods)
        - Not tested
    validations:
      required: true

  - type: textarea
    id: other_mods
    attributes:
      label: Other mods
      description: List other mods that might be relevant (or write "None").
      placeholder: Xaero's Minimap v21.6.0, Xaero's World Map v1.9.6, JEI vX.Y.Z
      render: text

  - type: textarea
    id: logs
    attributes:
      label: Logs (latest.log)
      description: Paste relevant logs here, or upload them to mclo.gs and paste the link.
      placeholder: Paste logs here or paste an mclo.gs link...
      render: shell

  - type: textarea
    id: additional_information
    attributes:
      label: Additional information
      description: Any extra context that might help (world type, singleplayer/multiplayer, server/modpack, etc.).
      placeholder: Add any other context here.

  - type: markdown
    attributes:
      value: |
        ### Screenshots / Videos
        Issue forms can’t upload files directly.
        After submitting, please attach screenshots or videos by dragging and dropping them into the issue description or a comment.
