name: Enhancement Request
description: Suggest an improvement to an existing feature
labels: [ "Status: Todo", "Type: Enhancement" ]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion.
        Please describe the improvement in concrete terms so it can be evaluated properly.

  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-flight checklist
      description: Please confirm the following before submitting.
      options:
        - label: I have searched the existing issues to make sure this is not a duplicate.
          required: true
        - label: I confirmed this is not already implemented in the latest version.
          required: true

  - type: textarea
    id: enhancement_description
    attributes:
      label: Enhancement summary
      description: Describe the improvement you would like to see.
      placeholder: I'd like to see...
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use case / motivation
      description: Explain when you would use this improvement and why it would be helpful.
      placeholder: This would help by...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution (optional)
      description: If you have an idea of how it could work (UI, behavior, settings, etc.), write it here.
      placeholder: e.g. Add a setting called "..." that does ...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives (optional)
      description: Any alternative approaches or workarounds you’ve tried.
      placeholder: e.g. I currently work around this by...

  - type: textarea
    id: additional_information
    attributes:
      label: Additional information (optional)
      description: Provide any other context or references (links, screenshots, related mods, etc.).
      placeholder: Additional details...
