modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    description = '''${mod_description}'''
    authors = "${mod_author}"
    logoFile="icon.png"
    displayURL="${mod_home_url}"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"

[[dependencies.${mod_id}]]
    modId = "waystones"
    type = "required"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "xaerominimap"
    type = "required"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "kotlinforforge"
    type = "required"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "yet_another_config_lib_v3"
    type = "required"
    ordering = "NONE"
    side = "BOTH"