name: Auto Approve
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  approve:
    if: |
      contains(fromJSON('["alinco8"]'), github.event.pull_request.user.login)
      && ! github.event.pull_request.draft
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Approve PR
        run: gh pr review ${{ github.event.pull_request.number }} --approve
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
